# DEFAULT CONFIG FOR cmus-status-line
# To write this config to the proper config file, run something like:
#     mkdir -p ~/.config/cmus-status-line
#     cmus-status-line dump-config > ~/.config/cmus-status-line/config.toml

format = """
%{ If(
    Or(IsStatus(Playing), IsStatus(Paused)),
    Container([
        Container([
            If(IsStatus(Playing),
                Text("")),
            If(IsStatus(Paused),
                Text("")),
            If(IsStatus(Stopped),
                Text("")),
        ]),

        If(
            IsStatus(Playing),
            Container([
                Truncate(Title, 60),
                Text(" - "),
                ProgressBar("■■■■■■■■■■■■■■■■■■■■■■■                        "),
            ]),
        ),

        If(
            IsStatus(Paused),
            Container([
                Title,
                Text(" ..........................."),
                ProgressBar("    "),
            ]),
        ),
    ]),
)}
"""
